UpdateCredentialConfig:
  InjiCertify_UpdateCredentialConfig_landregistry_minimum_attributes_1.1Model__all_Valid_Smoke:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credentials/configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_UpdateConfiguration_01
    description: Update Credential Configuration with extra field in credential subject
    checkErrorsOnlyInResponse: true
    restMethod: put
    validityCheckRequired: true
    inputTemplate: injicertify/CredentialConfig/UpdateCredentialConfiguration/UpdateCredentialConfiguration
    outputTemplate: injicertify/CredentialConfig/UpdateCredentialConfiguration/UpdateCredentialConfigurationResult
    input: '{
        "configurationId": "$ID:AddCredentialConfig_landregistry_minimum_attributes_1.1Model_all_Valid_Smoke_sid_id$",    
        "@context": [{"context_value": "https://www.w3.org/2018/credentials/v1"},{"context_value": "https://mosip.github.io/inji-config/contexts/landregistry-statement-context.json"}],
        "type": [{"type_value": "VerifiableCredential"}, {"type_value": "landstatement_minimumattributes"}],
        "credential_key1": "PermanentPreservationAreas",
        "credential_key2": "APPInConsolidatedRuralArea",
        "credential_value1": "${permanent_preservation_areas_app}",
        "credential_value2": "${app_in_consolidated_rural_area}",
        "credential_key3": "APPInNativeVegetationRemnantArea",
        "credential_key4": "RestrictedUseAreas",
        "credential_value3": "${app_in_native_vegetation_remnant_area}",
        "credential_value4": "${restricted_use_areas}",
        "credential_key5": "LegalReserveDeficitOrExcess",
        "credential_key6": "LegalReserveAreaToBeRestored",
        "credential_value5": "${legal_reserve_deficit_excess}",
        "credential_value6": "${legal_reserve_area_to_recompose}",
        "credential_key7": "PermanentPreservationAreasToBeRestored",
        "credential_key8": "RestrictedUseAreaToBeRestored",
        "credential_value7": "${permanent_preservation_areas_to_recompose}",
        "credential_value8": "${restricted_use_area_to_recompose}",
        "credential_key9": "EmbarggedAreaDescription",
        "credential_value9": "${embargoed_area_description}",
        "credential_key10": "ConservationUnitOverlapPercentage",
        "credential_value10": "${conservation_unit_overlap_percentage}",        
        "context": [{context: "https://www.w3.org/2018/credentials/v1"},{context: "https://mosip.github.io/inji-config/contexts/landregistry-statement-context.json"}],
        "credentialType": [{"credentialType": "VerifiableCredential"}, {"credentialType": "landstatement_minimumattributes"}],
        "didUrl": "did:web:likhitharl.github.io:vc:qainji#key-0",
        "keyManagerAppId": "CERTIFY_VC_SIGN_ED25519",
        "keyManagerRefId": "ED25519_SIGN",
        "signatureAlgo": "EdDSA",
        "credentialFormat": "ldp_vc",
        "display_name": "land statement Minimum attributes",
        "order": [
          {"order_values": "PermanentPreservationAreas"},
          {"order_values": "APPInNativeVegetationRemnantArea"},
          {"order_values": "RestrictedUseAreas"},
          {"order_values": "LegalReserveDeficitOrExcess"},
          {"order_values": "LegalReserveAreaToBeRestored"},
          {"order_values": "PermanentPreservationAreasToBeRestored"},
          {"order_values": "RestrictedUseAreaToBeRestored"},
          {"order_values": "EmbarggedAreaDescription"},
          {"order_values": "APPInConsolidatedRuralArea"}          
        ],
        "scope": "land_statement_vc_ldp",
        "credentialConfigKeyId": "landstatement_minimumattributes",        
        "cryptographic_binding_methods_supported": [{"cryptographic_binding_methods_supported_value": "did:jwk"}],
        "credential_signing_alg_values_supported": [{"credential_signing_alg_values_supported_value": "Ed25519Signature2020"}],
        "proof_signing_alg_values_supported": [{"algs": "RS256"}]
      }'
    output: '{
    "status": "active"    
    }'
  InjiCertify_UpdateCredentialConfig_landregistry_minimum_attributes_invalid_configId:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credentials/configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_UpdateConfiguration_02
    description: Update Credential Configuration with invalid config Id
    restMethod: put
    validityCheckRequired: true
    inputTemplate: injicertify/CredentialConfig/UpdateCredentialConfiguration/UpdateCredentialConfiguration
    outputTemplate: injicertify/error
    input: '{
        "configurationId": "123456789",    
       "@context": [{"context_value": "https://www.w3.org/2018/credentials/v1"},{"context_value": "https://mosip.github.io/inji-config/contexts/landregistry-statement-context.json"}],
        "type": [{"type_value": "VerifiableCredential"}, {"type_value": "landstatement_minimumattributes"}],
        "credential_key1": "PermanentPreservationAreas",
        "credential_key2": "APPInConsolidatedRuralArea",
        "credential_value1": "${permanent_preservation_areas_app}",
        "credential_value2": "${app_in_consolidated_rural_area}",
        "credential_key3": "APPInNativeVegetationRemnantArea",
        "credential_key4": "RestrictedUseAreas",
        "credential_value3": "${app_in_native_vegetation_remnant_area}",
        "credential_value4": "${restricted_use_areas}",
        "credential_key5": "LegalReserveDeficitOrExcess",
        "credential_key6": "LegalReserveAreaToBeRestored",
        "credential_value5": "${legal_reserve_deficit_excess}",
        "credential_value6": "${legal_reserve_area_to_recompose}",
        "credential_key7": "PermanentPreservationAreasToBeRestored",
        "credential_key8": "RestrictedUseAreaToBeRestored",
        "credential_value7": "${permanent_preservation_areas_to_recompose}",
        "credential_value8": "${restricted_use_area_to_recompose}",
        "credential_key9": "EmbarggedAreaDescription",
        "credential_value9": "${embargoed_area_description}",
        "context": [{context: "https://www.w3.org/2018/credentials/v1"},{context: "https://mosip.github.io/inji-config/contexts/landregistry-statement-context.json"}],
        "credentialType": [{"credentialType": "VerifiableCredential"}, {"credentialType": "landstatement_minimumattributes"}],
        "didUrl": "did:web:likhitharl.github.io:vc:qainji#key-0",
        "keyManagerAppId": "CERTIFY_VC_SIGN_ED25519",
        "keyManagerRefId": "ED25519_SIGN",
        "signatureAlgo": "EdDSA",
        "credentialFormat": "ldp_vc",
        "display_name": "land statement Minimum attributes",
        "order": [
          {"order_values": "PermanentPreservationAreas"},
          {"order_values": "APPInNativeVegetationRemnantArea"},
          {"order_values": "RestrictedUseAreas"},
          {"order_values": "LegalReserveDeficitOrExcess"},
          {"order_values": "LegalReserveAreaToBeRestored"},
          {"order_values": "PermanentPreservationAreasToBeRestored"},
          {"order_values": "RestrictedUseAreaToBeRestored"},
          {"order_values": "EmbarggedAreaDescription"},
          {"order_values": "APPInConsolidatedRuralArea"}          
        ],
        "scope": "land_statement_vc_ldp",
        "credentialConfigKeyId": "landstatement_minimumattributes",        
        "cryptographic_binding_methods_supported": [{"cryptographic_binding_methods_supported_value": "did:jwk"}],
        "credential_signing_alg_values_supported": [{"credential_signing_alg_values_supported_value": "Ed25519Signature2020"}],
        "proof_signing_alg_values_supported": [{"algs": "RS256"}]
      }'
    output: '{
      "errors": [
      {
       "errorCode": "Configuration not found with the provided id: 123456789"
       }
       ]    
    }'    