DeleteCredentialConfig:
  InjiCertify_DeleteCredentialConfig_landregistry_Cred1__Sd_jwt_valid_Smoke:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_DeleteCredentialConfig_01
    description: Delete Credential configuration credential type
    role: noauth    
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/Sd_Jwt/DeleteCredentialConfigurationSd_Jwt/DeleteCredentialConfigurationForSd_Jwt
    outputTemplate: injicertify/responseCode
    input: '{
        "configurationId": "$ID:AddCredentialConfig_landregistry_cred1_Sd_Jwt_all_Valid_Smoke_sid_id$"
      }'
    output: '{
	"responseCode": "200"    
    }'
  InjiCertify_DeleteCredentialConfig_landregistry_Cred2_Sd_jwt_valid_Smoke:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_DeleteCredentialConfig_02
    description: Delete Credential configuration for credential type 2
    role: noauth    
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/Sd_Jwt/DeleteCredentialConfigurationSd_Jwt/DeleteCredentialConfigurationForSd_Jwt
    outputTemplate: injicertify/responseCode
    input: '{
        "configurationId": "$ID:AddCredentialConfig_landregistry_cred2_Sd_Jwt_all_Valid_Smoke_sid_id$"
      }'
    output: '{
	"responseCode": "200"    
    }'
  InjiCertify_DeleteCredentialConfig_landregistry_Cred2_Sd_jwt_NoSdCLaims:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_DeleteCredentialConfig_03
    description: Delete Credential configuration for credential type 2
    role: noauth    
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/Sd_Jwt/DeleteCredentialConfigurationSd_Jwt/DeleteCredentialConfigurationForSd_Jwt
    outputTemplate: injicertify/responseCode
    input: '{
        "configurationId": "$ID:AddCredentialConfig_landregistry_cred1_Sd_Jwt_without_sdClaims_sid_id$"
      }'
    output: '{
	"responseCode": "200"    
    }'
  InjiCertify_DeleteCredentialConfig_landregistry_Cred2_Sd_jwt_randomClaims:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_DeleteCredentialConfig_04
    description: Delete Credential configuration for credential type 2
    role: noauth    
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/Sd_Jwt/DeleteCredentialConfigurationSd_Jwt/DeleteCredentialConfigurationForSd_Jwt
    outputTemplate: injicertify/responseCode
    input: '{
        "configurationId": "$ID:AddCredentialConfig_landregistry_cred1_Sd_Jwt_randomclaims_sid_id$"
      }'
    output: '{
	"responseCode": "200"    
    }'               