DeleteCredentialConfigurationForCSRCertificate:
  InjiCertify_Delete_landregistry_CSR_for_Cred1_2.0_valid_Smoke:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_Delete_Credential_Config_CSRCertificate_01
    description: Delete Credential configuration for land registry for csr certificate flow
    role: noauth    
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/CSRCertificate/DeleteCredentialConfigurationForCSRCertificate/DeleteCredentialConfigurationForCSRCertificate
    outputTemplate: injicertify/responseCode
    input: '{
        "configurationId": "$ID:Add_landregistry_CSR_for_Cred1_2.0_all_Valid_Smoke_sid_id$"
      }'
    output: '{
	"responseCode": "200"    
    }'

  InjiCertify_Delete_landregistry_CSR_for_Cred1_2.0_DataIntegrity_valid_Smoke:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_Delete_Credential_Config_CSRCertificate_02
    description: Delete Credential configuration for land registry for csr certificate flow
    role: noauth    
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/CSRCertificate/DeleteCredentialConfigurationForCSRCertificate/DeleteCredentialConfigurationForCSRCertificate
    outputTemplate: injicertify/responseCode
    input: '{
        "configurationId": "$ID:Add_landregistry_CSR_for_Cred1_2.0_dataIntegrity_all_Valid_Smoke_sid_id$"
      }'
    output: '{
	"responseCode": "200"    
    }'
    
  InjiCertify_Delete_landregistry_CSR_for_Cred2_1.1_valid_Smoke:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_Delete_Credential_Config_CSRCertificate_03
    description: Delete Credential configuration for land statement for csr certificate flow
    role: noauth    
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/CSRCertificate/DeleteCredentialConfigurationForCSRCertificate/DeleteCredentialConfigurationForCSRCertificate
    outputTemplate: injicertify/responseCode
    input: '{
        "configurationId": "$ID:Add_landregistry_CSR_for_Cred2_1.1_all_Valid_Smoke_sid_id$"
      }'
    output: '{
	"responseCode": "200"    
    }'

  InjiCertify_Delete_landregistry_CSR_for_Cred2_sd_jwt_valid_Smoke:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_Delete_Credential_Config_CSRCertificate_04
    description: Delete Credential configuration for land statement for csr certificate flow
    role: noauth    
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/CSRCertificate/DeleteCredentialConfigurationForCSRCertificate/DeleteCredentialConfigurationForCSRCertificate
    outputTemplate: injicertify/responseCode
    input: '{
        "configurationId": "$ID:AddCredentialConfig_landregistry_CSR_cred2_sd_jwt_all_Valid_Smoke_sid_id$"
      }'
    output: '{
	"responseCode": "200"    
    }'            