DeleteCredentialConfig:
  InjiCertify_Delete_landregistry_DataIntegrityProof_for_Cred1_valid_Smoke:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_DeleteCredentialConfig_01
    description: Delete Credential configuration for land statament data integrity proof
    role: noauth    
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/DataIntegrityProof/DeleteCredentialConfigurationForDataIntegrity/DeleteCredentialConfiguration
    outputTemplate: injicertify/responseCode
    input: '{
        "configurationId": "$ID:Add_landregistry_dataIntegrityProof_for_Cred1_2.0_all_Valid_Smoke_sid_id$"
      }'
    output: '{
	"responseCode": "200"    
    }'
  InjiCertify_Delete_landregistry_DataIntegrityProof_for_Cred2_valid_Smoke:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_DeleteCredentialConfig_02
    description: Delete Credential configuration for landregistry data integrity proof
    role: noauth    
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/DataIntegrityProof/DeleteCredentialConfigurationForDataIntegrity/DeleteCredentialConfiguration
    outputTemplate: injicertify/responseCode
    input: '{
        "configurationId": "$ID:Add_landregistry_dataIntegrityProof_for_Cred2_2.0_all_Valid_Smoke_sid_id$"
      }'
    output: '{
	"responseCode": "200"    
    }'
  InjiCertify_Delete_landregistry_DataIntegrityProof_for_Cred1_1.1_valid_Smoke:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_DeleteCredentialConfig_03
    description: Delete Credential configuration for land statement data integrity proof
    role: noauth    
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/DataIntegrityProof/DeleteCredentialConfigurationForDataIntegrity/DeleteCredentialConfiguration
    outputTemplate: injicertify/responseCode
    input: '{
        "configurationId": "$ID:Add_landregistry_dataIntegrityProof_for_Cred1_1.1_all_Valid_Smoke_sid_id$"
      }'
    output: '{
	"responseCode": "200"    
    }'
  InjiCertify_Delete_landregistry_DataIntegrityProof_for_Cred2_1.1_valid_Smoke:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_DeleteCredentialConfig_04
    description: Delete Credential configuration for landregistry data integrity proof
    role: noauth    
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/DataIntegrityProof/DeleteCredentialConfigurationForDataIntegrity/DeleteCredentialConfiguration
    outputTemplate: injicertify/responseCode
    input: '{
        "configurationId": "$ID:Add_landregistry_dataIntegrityProof_for_Cred2_1.1_all_Valid_Smoke_sid_id$"
      }'
    output: '{
	"responseCode": "200"    
    }'
  InjiCertify_Delete_landregistry_DataIntegrityProof_for_invalidScope:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_DeleteCredentialConfig_05
    description: Delete Credential configuration for landregistry data integrity proof
    role: noauth    
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/DataIntegrityProof/DeleteCredentialConfigurationForDataIntegrity/DeleteCredentialConfiguration
    outputTemplate: injicertify/responseCode
    input: '{
        "configurationId": "$ID:Add_landregistry_dataIntegrityProof_for_Cred1_2.0_invalid_scope_sid_id$"
      }'
    output: '{
	"responseCode": "200"    
    }'         