AddCredentialConfigForRevocation:
  InjiCertify_Add_landregistry_Revocation_for_Cred1_2.0_all_Valid_Smoke_sid:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations
    uniqueIdentifier: TC_InjiCertify_revocation_01
    description: Add credential configuration for revocation scenarios
    role: noauth    
    restMethod: post
    inputTemplate: injicertify/Revocation/AddCredentialConfigForRevocation/AddCredentialConfigurationLandRegistry2.0
    outputTemplate: injicertify/Revocation/AddCredentialConfigForRevocation/AddCredentialConfigurationResult
    input: '{
        "@context": [{"context_value": "https://www.w3.org/ns/credentials/v2"}, {"context_value": "https://mosip.github.io/inji-config/contexts/landregistry-revocation-context.json"}],
        "type": [{"type_value": "VerifiableCredential"}, {"type_value": "landregistry_revocation"}],
        "credential_key1": "PermanentPreservationAreas",
        "credential_key2": "APPInConsolidatedRuralArea",
        "credential_value1": "${permanent_preservation_areas_app}",
        "credential_value2": "${app_in_consolidated_rural_area}",
        "credential_key3": "APPInNativeVegetationRemnantArea",
        "credential_key4": "RestrictedUseAreas",
        "credential_value3": "${app_in_native_vegetation_remnant_area}",
        "credential_value4": "${restricted_use_areas}",
        "credential_key5": "LegalReserveDeficitOrExcess",
        "credential_key6": "LegalReserveAreaToBeRestored",
        "credential_value5": "${legal_reserve_deficit_excess}",
        "credential_value6": "${legal_reserve_area_to_recompose}",
        "credential_key7": "PermanentPreservationAreasToBeRestored",
        "credential_key8": "RestrictedUseAreaToBeRestored",
        "credential_value7": "${permanent_preservation_areas_to_recompose}",
        "credential_value8": "${restricted_use_area_to_recompose}",
        "credential_key9": "EmbarggedAreaDescription",
        "credential_value9": "${embargoed_area_description}",
        "credential_key10": "NumberOfCAR",
        "credential_value10": "${car_registration_number}",
        "credential_key11": "RegistrationDate",
        "credential_value11": "${registration_date}",
        "credential_key12": "LastModificationDate",
        "credential_value12": "${date_of_last_amendment}",
        "credential_key13": "RuralPropertyArea",
        "credential_value13": "${rural_property_area}",
        "credential_key14": "Latitude",
        "credential_value14": "${latitude}",
        "credential_key15": "Longitude",
        "credential_value15": "${longitude}",
        "credential_key16": "Municipality",
        "credential_value16": "${municipality}",
        "credential_key17": "ExternalCondition",
        "credential_value17": "${external_condition}",
        "credential_key18": "RegistrationStatus",
        "credential_value18": "${registration_status}",
        "credential_key19": "PRACondition",
        "credential_value19": "${pra_condition}",
        "credential_key20": "GroundCoverage",
        "credential_value20": "${land_cover}",
        "credential_key21": "NativeVegetationRemnantArea",
        "credential_value21": "${native_vegetation_remnant_area}",
        "credential_key22": "ConsolidatedRuralArea",
        "credential_value22": "${consolidated_rural_area}",
        "credential_key23": "AdministrativeEasementArea",
        "credential_value23": "${administrative_easement_area}",
        "credential_key24": "LegalReserveLocation",
        "credential_value24": "${location_of_legal_reserve}",
        "credential_key25": "RegisteredLegalReserveArea",
        "credential_value25": "${registered_legal_reserve_area}",
        "credential_key26": "GeoreferencedLegalReserveArea",
        "credential_value26": "${georeferenced_legal_reserve_area}",
        "credential_key27": "ApprovedUnregisteredLegalReserveArea",
        "credential_value27": "${approved_legal_reserve_area_not_registered}",
        "credential_key28": "ProposedLegalReserveArea",
        "credential_value28": "${proposed_legal_reserve_area}",
        "credential_key29": "TotalDeclaredLegalReserve",
        "credential_value29": "${total_legal_reserve_declared}",
        "credential_key30": "EmbarggedAreaProcessingDate",
        "credential_value30": "${embargoed_area_processing_date}",
        "credential_key31": "EmbarggedAreaOverlap",
        "credential_value31": "${embargoed_area_overlap}",
        "credential_key32": "EmbarggedAreaOverlapPercentage",
        "credential_value32": "${embargoed_area_overlap_percentage}",
        "credential_key33": "ConservationUnitDescription",
        "credential_value33": "${conservation_unit_description}",
        "credential_key34": "ConservationUnitProcessingDate",
        "credential_value34": "${conservation_unit_processing_date}",
        "credential_key35": "ConservationUnitOverlapArea",
        "credential_value35": "${conservation_unit_overlap_area}",
        "credential_key36": "ConservationUnitOverlapPercentage",
        "credential_value36": "${conservation_unit_overlap_percentage}",        
        "contextURLs": [{"contextURLs": "https://www.w3.org/ns/credentials/v2"}, {"contextURLs": "https://mosip.github.io/inji-config/contexts/landregistry-revocation-context.json"}],
        "credentialTypes": [{"credentialTypes": "VerifiableCredential"}, {"credentialTypes": "landregistry_revocation"}],
        "didUrl": "did:web:mosip.github.io:inji-config:collab:landregistry",
        "keyManagerAppId": "CERTIFY_VC_SIGN_ED25519",
        "keyManagerRefId": "ED25519_SIGN",
        "signatureAlgo": "EdDSA",
        "signatureCryptoSuite": "eddsa-rdfc-2022",        
        "credentialFormat": "ldp_vc",
        "display_name": "land statement for data integrity",
        "displayOrder": [
          {"displayOrder_values": "NumberOfCAR"},
          {"displayOrder_values": "RegistrationDate"},
          {"displayOrder_values": "LastModificationDate"},
          {"displayOrder_values": "RuralPropertyArea"},
          {"displayOrder_values": "Latitude"},
          {"displayOrder_values": "Longitude"},
          {"displayOrder_values": "Municipality"},
          {"displayOrder_values": "ExternalCondition"},
          {"displayOrder_values": "RegistrationStatus"},
          {"displayOrder_values": "PRACondition"},
          {"displayOrder_values": "GroundCoverage"},
          {"displayOrder_values": "NativeVegetationRemnantArea"},
          {"displayOrder_values": "ConsolidatedRuralArea"},
          {"displayOrder_values": "AdministrativeEasementArea"},
          {"displayOrder_values": "LegalReserveLocation"},
          {"displayOrder_values": "RegisteredLegalReserveArea"},
          {"displayOrder_values": "GeoreferencedLegalReserveArea"},
          {"displayOrder_values": "ApprovedUnregisteredLegalReserveArea"},
          {"displayOrder_values": "ProposedLegalReserveArea"},
          {"displayOrder_values": "TotalDeclaredLegalReserve"},
          {"displayOrder_values": "PermanentPreservationAreas"},
          {"displayOrder_values": "APPInConsolidatedRuralArea"},
          {"displayOrder_values": "APPInNativeVegetationRemnantArea"},
          {"displayOrder_values": "RestrictedUseAreas"},
          {"displayOrder_values": "LegalReserveDeficitOrExcess"},
          {"displayOrder_values": "LegalReserveAreaToBeRestored"},
          {"displayOrder_values": "PermanentPreservationAreasToBeRestored"}                             
        ],
        "scope": "land_statement_vc_ldp",
        "credentialConfigKeyId": "landstatement_revocation_2.0"        
      }'
    output: '{
    "status": "active"  
    }'                      