modules:
  injicertify:
    enabled: true
    image:
      repository: mosipid/apitest-inji-certify
      tag: 0.10.0
      pullPolicy: Always
  prereg:
    enabled: false
    masterdata:
      enabled: false
    idrepo:
      enabled: false
    partner:
      enabled: false
    pms:
    resident:
      enabled: false
    auth:
      enabled: false
    esignet:
      enabled: false
    mimoto:
      enabled: false
