GetCredentialConfig:
  InjiCertify_GetcredentialConfig_all_Valid_Smoke:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credentials/configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_GetCredentialConfig_01
    description: Get credential configuration
    checkErrorsOnlyInResponse: true
    restMethod: get
    validityCheckRequired: true
    inputTemplate: injicertify/CredentialConfig/GetCredentialConfiguration/GetCredentialConfiguration
    outputTemplate: injicertify/CredentialConfig/GetCredentialConfiguration/GetCredentialConfigurationResult
    input: '{
          "configurationId": "$ID:AddCredentialConfig_landregistry_minimum_attributes_1.1Model_all_Valid_Smoke_sid_id$"
      }'
    output: '{
    }'
    
  InjiCertify_GetcredentialConfig_invalid_config_Id:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credentials/configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_GetCredentialConfig_02
    description: Get credential configuration with invalid config Id
    restMethod: get
    validityCheckRequired: true
    inputTemplate: injicertify/CredentialConfig/GetCredentialConfiguration/GetCredentialConfiguration
    outputTemplate: injicertify/error
    input: '{
          "configurationId": "123456789"
      }'
    output: '{
      "errors": [
      {
       "errorCode": "Configuration not found with the provided id: 123456789"
       }
       ]
    }'
  InjiCertify_GetcredentialConfig_2.0_all_Valid_Smoke:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credentials/configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_GetCredentialConfig_03
    description: Get credential configuration for 2.0 model credentialtype
    checkErrorsOnlyInResponse: true
    restMethod: get
    validityCheckRequired: true
    inputTemplate: injicertify/CredentialConfig/GetCredentialConfiguration/GetCredentialConfiguration
    outputTemplate: injicertify/CredentialConfig/GetCredentialConfiguration/GetCredentialConfigurationResult
    input: '{
          "configurationId": "$ID:AddCredentialConfig_landregistry_minimum_attributes_2.0Model_all_Valid_Smoke_sid_id$"
      }'
    output: '{
    }'        