GetCredentialConfig:
  InjiCertify_GetcredentialConfig_landregistry_all_Valid_Smoke:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_GetCredentialConfig_01
    description: Get credential configuration
    role: noauth    
    checkErrorsOnlyInResponse: true
    restMethod: get
    additionalDependencies: TC_InjiCertify_addCredentialtype_01
    inputTemplate: injicertify/CredentialConfig/GetCredentialConfiguration/GetCredentialConfiguration
    outputTemplate: injicertify/CredentialConfig/GetCredentialConfiguration/GetCredentialConfigurationResult
    input: '{
          "configurationId": "$ID:AddCredentialConfig_landregistry_minimum_attributes_1.1Model_all_Valid_Smoke_sid_id$"
      }'
    output: '{
    }'
    
  InjiCertify_GetcredentialConfig_landregistry_invalid_config_Id:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_GetCredentialConfig_02
    description: Get credential configuration with invalid config Id
    role: noauth    
    restMethod: get
    inputTemplate: injicertify/CredentialConfig/GetCredentialConfiguration/GetCredentialConfiguration
    outputTemplate: injicertify/error
    input: '{
          "configurationId": "123456789"
      }'
    output: '{
      "errors": [
      {
       "errorCode": "invalid_request"
       }
       ]
    }'
  InjiCertify_GetcredentialConfig_landregistry_2.0_all_Valid_Smoke:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_GetCredentialConfig_03
    description: Get credential configuration for 2.0 model credentialtype
    role: noauth    
    checkErrorsOnlyInResponse: true
    restMethod: get
    additionalDependencies: TC_InjiCertify_addCredentialtype_02
    inputTemplate: injicertify/CredentialConfig/GetCredentialConfiguration/GetCredentialConfiguration
    outputTemplate: injicertify/CredentialConfig/GetCredentialConfiguration/GetCredentialConfigurationResult
    input: '{
          "configurationId": "$ID:AddCredentialConfig_landregistry_minimum_attributes_2.0Model_all_Valid_Smoke_sid_id$"
      }'
    output: '{
    }'        