DeleteCredentialConfigurationForRevocation:
  InjiCertify_Delete_landregistry_Revocation_for_Cred1_valid_Smoke:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_Delete_Credential_Config_Revocation_01
    description: Delete Credential configuration for land statament for revocation flow
    role: noauth    
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/Revocation/DeleteCredentialConfigurationForRevocation/DeleteCredentialConfigurationForRevocation
    outputTemplate: injicertify/responseCode
    input: '{
        "configurationId": "$ID:Add_landregistry_Revocation_for_Cred1_2.0_all_Valid_Smoke_sid_id$"
      }'
    output: '{
	"responseCode": "200"    
    }'