DeleteCredentialConfig:
  InjiCertify_DeleteCredentialConfig_landregistry_minimum_attributes_1.1Model_all_Valid_Smoke:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_DeleteCredentialConfig_01
    description: Delete Credential configuration
    role: noauth    
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/CredentialConfig/DeleteCredentialConfiguration/DeleteCredentialConfiguration
    outputTemplate: injicertify/responseCode
    input: '{
        "configurationId": "$ID:AddCredentialConfig_landregistry_minimum_attributes_1.1Model_all_Valid_Smoke_sid_id$"
      }'
    output: '{
	"responseCode": "200"    
    }'   
  InjiCertify_DeleteCredentialConfig_landregistry_minimum_attributes_Invalid_configId:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_DeleteCredentialConfig_02
    description: Delete Credential configuration with invalid Config id
    role: noauth    
    restMethod: delete
    inputTemplate: injicertify/CredentialConfig/DeleteCredentialConfiguration/DeleteCredentialConfiguration
    outputTemplate: injicertify/error
    input: '{
        "configurationId": "1234567890"
      }'
    output: '{
      "errors": [
      {
       "errorCode": "invalid_request"
       }
       ]
    }'
  InjiCertify_DeleteCredentialConfig_landregistry_minimum_attributes_2.0Model:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_DeleteCredentialConfig_03
    description: Delete Credential configuration for 2.0 model
    role: noauth    
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/CredentialConfig/DeleteCredentialConfiguration/DeleteCredentialConfiguration
    outputTemplate: injicertify/responseCode
    input: '{
        "configurationId": "$ID:AddCredentialConfig_landregistry_minimum_attributes_2.0Model_all_Valid_Smoke_sid_id$"
      }'
    output: '{
	"responseCode": "200" 
    }'
  InjiCertify_DeleteCredentialConfig_landregistry_minimum_attributes_2.0Model_SpecialCharacters:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_DeleteCredentialConfig_04
    description: Delete Credential configuration for 2.0 model with special characters
    role: noauth    
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/CredentialConfig/DeleteCredentialConfiguration/DeleteCredentialConfiguration
    outputTemplate: injicertify/responseCode
    input: '{
        "configurationId": "$ID:AddCredentialConfig_landregistry_minimum_attributes_2.0Model_SpecialCharacters_sid_id$"
      }'
    output: '{
	"responseCode": "200"    
    }'
  InjiCertify_DeleteCredentialConfig_landregistry_minimum_attributes_2.0Model_LengthyVcType:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_DeleteCredentialConfig_05
    description: Delete Credential configuration for 2.0 model with lengthyVc type
    role: noauth    
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/CredentialConfig/DeleteCredentialConfiguration/DeleteCredentialConfiguration
    outputTemplate: injicertify/responseCode
    input: '{
        "configurationId": "$ID:AddCredentialConfig_landregistry_minimum_attributes_2.0Model_LengthyVcType_sid_id$"
      }'
    output: '{
	"responseCode": "200"    
    }'
    
  InjiCertify_DeleteCredentialConfig_landregistry_minimum_attributes_2.0Model_MultipleVcType:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_DeleteCredentialConfig_06
    description: Delete Credential configuration for 2.0 model with Multiple VC type
    role: noauth    
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/CredentialConfig/DeleteCredentialConfiguration/DeleteCredentialConfiguration
    outputTemplate: injicertify/responseCode
    input: '{
        "configurationId": "$ID:AddCredentialConfig_landregistry_minimum_attributes_2.0Model_multiple_VCTypes_sid_id$"
      }'
    output: '{
	"responseCode": "200"    
    }'
  InjiCertify_DeleteCredentialConfig_landregistry_minimum_attributes_2.0Model_randomscope:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_DeleteCredentialConfig_07
    description: Delete Credential configuration for 2.0 model with random scope
    role: noauth    
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/CredentialConfig/DeleteCredentialConfiguration/DeleteCredentialConfiguration
    outputTemplate: injicertify/responseCode
    input: '{
        "configurationId": "$ID:AddCredentialConfig_landregistry_minimum_attributes_2.0Model_random_Scope_sid_id$"
      }'
    output: '{
	"responseCode": "200"    
    }'
  InjiCertify_DeleteCredentialConfig_landregistry_eccr1:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_DeleteCredentialConfig_08
    description: Delete Credential configuration for eccr1 key
    role: noauth    
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/CredentialConfig/DeleteCredentialConfiguration/DeleteCredentialConfiguration
    outputTemplate: injicertify/responseCode
    input: '{
        "configurationId": "$ID:AddCredentialConfig_landregistry_eccr1_1.1Model_all_Valid_sid_id$"
      }'
    output: '{
	"responseCode": "200"    
    }'
  InjiCertify_DeleteCredentialConfig_landregistry_ecck1:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_DeleteCredentialConfig_09
    description: Delete Credential configuration for ecck1 key
    role: noauth    
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/CredentialConfig/DeleteCredentialConfiguration/DeleteCredentialConfiguration
    outputTemplate: injicertify/responseCode
    input: '{
        "configurationId": "$ID:AddCredentialConfig_landregistry_ecck1_2.0Model_all_Valid_sid_id$"
      }'
    output: '{
	"responseCode": "200"    
    }'                                  