DeleteCredentialConfig:
  InjiCertify_DeleteCredentialConfig_landregistry_EccR1_2.0_valid_Smoke:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credentials/configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_DeleteCredentialConfig_01
    description: Delete Credential configuration
    role: noauth    
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    validityCheckRequired: true
    inputTemplate: injicertify/EccR1/DeleteCredentialConfiguration/DeleteCredentialConfiguration
    outputTemplate: injicertify/responseCode
    input: '{
        "configurationId": "$ID:AddCredentialConfig_landregistry_EccR1_2.0Model__all_Valid_Smoke_sid_id$"
      }'
    output: '{
	"responseCode": "200"    
    }'
  InjiCertify_DeleteCredentialConfig_landregistry_EccR1_1.1_valid_Smoke:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credentials/configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_DeleteCredentialConfig_01
    description: Delete Credential configuration
    role: noauth    
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    validityCheckRequired: true
    inputTemplate: injicertify/EccR1/DeleteCredentialConfiguration/DeleteCredentialConfiguration
    outputTemplate: injicertify/responseCode
    input: '{
        "configurationId": "$ID:AddCredentialConfig_landregistry_EccR_1_1.1Model_all_Valid_Smoke_sid_id$"
      }'
    output: '{
	"responseCode": "200"    
    }'    