DeleteCredentialConfig:
  InjiCertify_DeleteCredentialConfig_landregistry_EccR1_2.0_valid_Smoke:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_DeleteCredentialConfig_15
    description: Delete Credential configuration
    role: noauth    
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/EccR1/DeleteCredentialConfiguration/DeleteCredentialConfiguration
    outputTemplate: injicertify/responseCode
    input: '{
        "configurationId": "$ID:AddCredentialConfig_landregistry_EccR1_2.0Model__all_Valid_Smoke_sid_id$"
      }'
    output: '{
	"responseCode": "200"    
    }'
  InjiCertify_DeleteCredentialConfig_landregistry_EccR1_1.1_valid_Smoke:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_DeleteCredentialConfig_16
    description: Delete Credential configuration
    role: noauth    
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/EccR1/DeleteCredentialConfiguration/DeleteCredentialConfiguration
    outputTemplate: injicertify/responseCode
    input: '{
        "configurationId": "$ID:AddCredentialConfig_landregistry_EccR1_1.1Model_all_Valid_Smoke_sid_id$"
      }'
    output: '{
	"responseCode": "200"    
    }'
  InjiCertify_DeleteCredentialConfig_landregistry_EccR1_1.1_integrity_valid_Smoke:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_DeleteCredentialConfig_17
    description: Delete Credential configuration
    role: noauth    
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/EccR1/DeleteCredentialConfiguration/DeleteCredentialConfiguration
    outputTemplate: injicertify/responseCode
    input: '{
        "configurationId": "$ID:AddCredentialConfig_landregistry_EccR1_1.1_integrity_all_Valid_sid_id$"
      }'
    output: '{
	"responseCode": "200"    
    }'
  InjiCertify_DeleteCredentialConfig_landregistry_EccK1_2.0_valid_Smoke:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_DeleteCredentialConfig_03
    description: Delete Credential configuration
    role: noauth    
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/EccR1/DeleteCredentialConfiguration/DeleteCredentialConfiguration
    outputTemplate: injicertify/responseCode
    input: '{
        "configurationId": "$ID:AddCredentialConfig_landregistry_EccK1_2.0_Model_all_Valid_Smoke_sid_id$"
      }'
    output: '{
	"responseCode": "200"    
    }'             