AddCredentialConfig:
  InjiCertify_AddCredentialConfig_landregistry_EccR1_2.0Model__all_Valid_Smoke_sid:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credentials/configurations
    uniqueIdentifier: TC_InjiCertify_EccR1_Signature_01
    description: Add credential configuration for eccR1 signature
    role: noauth    
    checkErrorsOnlyInResponse: true
    restMethod: post
    validityCheckRequired: true
    inputTemplate: injicertify/EccR1/AddCredentialConfigEccR1/AddCredentialConfiguration2.0Model
    outputTemplate: injicertify/EccR1/AddCredentialConfigEccR1/AddCredentialConfigurationResult
    input: '{
        "@context": [{"context_value": "https://www.w3.org/ns/credentials/v2"},{"context_value": "https://mosip.github.io/inji-config/contexts/landregistry-statement-context-EccR1.json"}],
        "type": [{"type_value": "VerifiableCredential"}, {"type_value": "landstatement_EccR1"}],
        "credential_key1": "PermanentPreservationAreas",
        "credential_key2": "APPInConsolidatedRuralArea",
        "credential_value1": "${permanent_preservation_areas_app}",
        "credential_value2": "${app_in_consolidated_rural_area}",
        "credential_key3": "APPInNativeVegetationRemnantArea",
        "credential_key4": "RestrictedUseAreas",
        "credential_value3": "${app_in_native_vegetation_remnant_area}",
        "credential_value4": "${restricted_use_areas}",
        "credential_key5": "LegalReserveDeficitOrExcess",
        "credential_key6": "LegalReserveAreaToBeRestored",
        "credential_value5": "${legal_reserve_deficit_excess}",
        "credential_value6": "${legal_reserve_area_to_recompose}",
        "credential_key7": "PermanentPreservationAreasToBeRestored",
        "credential_key8": "RestrictedUseAreaToBeRestored",
        "credential_value7": "${permanent_preservation_areas_to_recompose}",
        "credential_value8": "${restricted_use_area_to_recompose}",
        "credential_key9": "EmbarggedAreaDescription",
        "credential_value9": "${embargoed_area_description}",
        "context": [{context: "https://www.w3.org/ns/credentials/v2"},{context: "https://mosip.github.io/inji-config/contexts/landregistry-statement-context-EccR1.json"}],
        "credentialType": [{"credentialType": "VerifiableCredential"}, {"credentialType": "landstatement_EccR1"}],
        "didUrl": "did:web:likhitharl.github.io:vc:qainji#key-0",
        "keyManagerAppId": "CERTIFY_VC_SIGN_EC_R1",
        "keyManagerRefId": "EC_SECP256R1_SIGN",
        "signatureAlgo": "ES256",
        "credentialFormat": "ldp_vc",
        "display_name": "landstatement_EccR1",
        "order": [
          {"order_values": "PermanentPreservationAreas"},
          {"order_values": "APPInNativeVegetationRemnantArea"},
          {"order_values": "RestrictedUseAreas"},
          {"order_values": "LegalReserveDeficitOrExcess"},
          {"order_values": "LegalReserveAreaToBeRestored"},
          {"order_values": "PermanentPreservationAreasToBeRestored"},
          {"order_values": "RestrictedUseAreaToBeRestored"},
          {"order_values": "EmbarggedAreaDescription"},
          {"order_values": "APPInConsolidatedRuralArea"}          
        ],
        "scope": "land_statement_vc_ldp",
        "credentialConfigKeyId": "landstatement_EccR1_2.0",        
        "cryptographic_binding_methods_supported": [{"cryptographic_binding_methods_supported_value": "did:jwk"}],
        "credential_signing_alg_values_supported": [{"credential_signing_alg_values_supported_value": "EcdsaSecp256r1Signature2019"}],
        "proof_signing_alg_values_supported": [{"algs": "RS256"}, {"algs": "PS256"}, {"algs": "Ed25519"}, {"algs": "ES256"}]
      }'
    output: '{
    "status": "active"  
    }'
  InjiCertify_AddCredentialConfig_landregistry_EccR_1_1.1Model_all_Valid_Smoke_sid:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credentials/configurations
    uniqueIdentifier: TC_InjiCertify_EccR1_Signature_02
    description: Add credential configuration for eccR1 signature for 1.1 Model
    role: noauth    
    checkErrorsOnlyInResponse: true
    restMethod: post
    validityCheckRequired: true
    inputTemplate: injicertify/EccR1/AddCredentialConfigEccR1/AddCredentialConfiguration1.1Model
    outputTemplate: injicertify/EccR1/AddCredentialConfigEccR1/AddCredentialConfigurationResult
    input: '{
        "@context": [{"context_value": "https://www.w3.org/2018/credentials/v1"},{"context_value": "https://mosip.github.io/inji-config/contexts/landregistry-statement-context-EccR1.json"}],
        "type": [{"type_value": "VerifiableCredential"}, {"type_value": "landstatement_EccR1"}],
        "credential_key1": "PermanentPreservationAreas",
        "credential_key2": "APPInConsolidatedRuralArea",
        "credential_value1": "${permanent_preservation_areas_app}",
        "credential_value2": "${app_in_consolidated_rural_area}",
        "credential_key3": "APPInNativeVegetationRemnantArea",
        "credential_key4": "RestrictedUseAreas",
        "credential_value3": "${app_in_native_vegetation_remnant_area}",
        "credential_value4": "${restricted_use_areas}",
        "credential_key5": "LegalReserveDeficitOrExcess",
        "credential_key6": "LegalReserveAreaToBeRestored",
        "credential_value5": "${legal_reserve_deficit_excess}",
        "credential_value6": "${legal_reserve_area_to_recompose}",
        "credential_key7": "PermanentPreservationAreasToBeRestored",
        "credential_key8": "RestrictedUseAreaToBeRestored",
        "credential_value7": "${permanent_preservation_areas_to_recompose}",
        "credential_value8": "${restricted_use_area_to_recompose}",
        "credential_key9": "EmbarggedAreaDescription",
        "credential_value9": "${embargoed_area_description}",
        "context": [{context: "https://www.w3.org/2018/credentials/v1"},{context: "https://mosip.github.io/inji-config/contexts/landregistry-statement-context-EccR1.json"}],
        "credentialType": [{"credentialType": "VerifiableCredential"}, {"credentialType": "landstatement_EccR1"}],
        "didUrl": "did:web:likhitharl.github.io:vc:qainji#key-0",
        "keyManagerAppId": "CERTIFY_VC_SIGN_EC_R1",
        "keyManagerRefId": "EC_SECP256R1_SIGN",
        "signatureAlgo": "ES256",
        "credentialFormat": "ldp_vc",
        "display_name": "landstatement_EccR1",
        "order": [
          {"order_values": "PermanentPreservationAreas"},
          {"order_values": "APPInNativeVegetationRemnantArea"},
          {"order_values": "RestrictedUseAreas"},
          {"order_values": "LegalReserveDeficitOrExcess"},
          {"order_values": "LegalReserveAreaToBeRestored"},
          {"order_values": "PermanentPreservationAreasToBeRestored"},
          {"order_values": "RestrictedUseAreaToBeRestored"},
          {"order_values": "EmbarggedAreaDescription"},
          {"order_values": "APPInConsolidatedRuralArea"}          
        ],
        "scope": "land_statement_vc_ldp",
        "credentialConfigKeyId": "landstatement_EccR1_1.1",        
        "cryptographic_binding_methods_supported": [{"cryptographic_binding_methods_supported_value": "did:jwk"}],
        "credential_signing_alg_values_supported": [{"credential_signing_alg_values_supported_value": "EcdsaSecp256r1Signature2019"}],
        "proof_signing_alg_values_supported": [{"algs": "RS256"}, {"algs": "PS256"}, {"algs": "Ed25519"}, {"algs": "ES256"}]
      }'
    output: '{
    "status": "active"  
    }'    